<?php 
/* This is an autogenerated phplicensewatcher config-file */
/* A good commented config-file is included in the distribution (in case you want to modify it manually. */
$showversion=True;
$lmutil_loc="/usr/local/bin/lmutil";
$rrdtool_bin="/usr/bin/rrdtool";
// $i4blt_loc="/opt/lum/ls/bin/i4blt";
$LUM_timeout=4;
$notify_address="john.doe@scs.ch";
$lead_time=10;
$disable_autorefresh=0;
$disable_license_removal=0;
$collection_interval=15;
$db_type="mysql";
$db_hostname="mariadb";
$db_username="lmutilmon";
$db_password="";
$db_database="licenses";
$dsn = "mysqli://$db_username:$db_password@$db_hostname/$db_database";
$colors="#ffffdd,#ff9966, #ffffaa,#ccccff,#cccccc,#ffcc66,#99ff99,#eeeeee,#66ffff,#ccffff, #ffff66, #ffccff,#ff66ff, yellow,lightgreen,lightblue";
$smallgraph="300,200";
$largegraph="600,300";
$legendpoints="";
$servers[]="";
$description[]="";
$log_file[]="";
$log_file[]="";
$log_file[]="";
$lmstat_loc=$lmutil_loc . " lmstat"; 

$license_feature[] = "msimhdlsim";
$feature_description[] = "HDL Questa";

?>
